(* old test case name: code143.sml *)

exception e of int
val e = e
